# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0025_auto_20170721_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qc',
            name='lower_range',
        ),
        migrations.RemoveField(
            model_name='qc',
            name='upper_range',
        ),
    ]
