# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0027_auto_20170801_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=2, verbose_name='Sex'),
        ),
    ]
