# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0028_auto_20170801_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcdata',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qcdata',
            name='qc_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
